### ISSUE TITLE
Modify URLSessionConfiguration

### ISSUE THREAD

**Issue by dducro** [xsolve-pl/swift-api#17]
Hey,

I need to change some configurations in URLSessionConfiguration.
It would be great to have an option to change the configuration per request.
Or to have additional options (configurable) beside foreground/background.

As a quick fix I modified RequestServiceConfiguration.swift with some values that are set for every request at the moment.

Do you have plans of adding this feature in the feature?

Thanks!

**Comment by dducro** [comment]
I used ApiManager.swift as a starting point for my implementation.

**Comment by MarekKojder** [comment]
Hi,
thank you for feedback. Sure, let me think about it, and I'll come back to you with the solution proposal.

**Comment by dducro** [comment]
Thanks for your reply,
Nice to here that you're open to feedback regarding URLSessionConfiguration.

Do you have thoughts on this feature request?
If you need any help with a solution proposal, let me know, I could also look into it.

**Comment by MarekKojder** [comment]
Hello @dducro,
sorry for such delay, I had no time to work on that.
In PR #19 i introduced my proposition of resolving that issue. Please take a look and feel free to comment or let me know what do you think about it :)

**Comment by dducro** [comment]
I understand, no problem!
I looked at it and think this is a great solution to my issue :)
Thanks for implementing it!

**Comment by MarekKojder** [comment]
Code is now available in version 1.1.5. I'm closing this issue.
